project:
  type: website

website:
  title: "Math378_Project_new"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: eda.qmd
        text: Penguins EDA
      - href: model-vetiver.qmd
        text: Model

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

