name: Build and Publish Quarto Website

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jupyter
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      - name: Setup R
        uses: r-lib/actions/setup-r@v1
      
      - name: Install R packages with renv
        run: |
          install.packages('renv')
          renv::restore()
      
      - name: Install Quarto
        run: |
          curl -LO "https://github.com/quarto-dev/quarto-cli/releases/download/v1.0.25/quarto-1.0.25-linux-amd64.deb"
          sudo dpkg -i quarto-1.0.25-linux-amd64.deb
      
      - name: Render Quarto Project
        run: quarto render

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
